#### Build Step ####
FROM golang:1.9-alpine as builder

WORKDIR src/git.containerum.net/ch/api-gateway
COPY . .

RUN CGO_ENABLED=0 go build -v -o /bin/ch-gateway --tags "stub" cmd/*

#### Run Step ####
# FROM scratch
FROM ubuntu

# Copy bin
COPY --from=builder /bin/ch-gateway /

# Set envs
ENV GATEWAY_DEBUG=true \
    TLS_CERT="cert.pem" \
    TLS_KEY="key.pem"

# run app
ENTRYPOINT ["/ch-gateway"]

EXPOSE 8082
